name: jaxvacua_metal
channels:
  - conda-forge
dependencies:
  # JAXVacua dependencies
  - python
  - numpy
  - scipy
  - pandas
  - normaliz
  - cvxopt
  - python-flint
  - pplpy
  - joblib
  - tqdm
  - qpsolvers
  - requests
  - osqp
  - pip
  - pip:
    - jaxlib
    - jax-metal
    - optax
    - jaxpolylog>=0.3.0
    - ortools
    - triangulumancer
    - pypalp
    - cygv
    - gurobipy
    - cytools
  # Common useful tools
  - jupyterlab
  - matplotlib
  - seaborn
  # Tests
  - chex
  - pytest