# ==============================================================================
# This code is written by Andreas Schachner.
#
# If any questions arise, please feel free to reach out to me (Andreas) either at
# andreas.schachner@gmx.net or at as3475@cornell.edu .
# ==============================================================================
#
# ------------------------------------------------------------------------------
# This file holds functions for ....
# ------------------------------------------------------------------------------

#Standard libraries
# Important standard libraries
import os, sys, warnings
import numpy as np
import itertools
import getopt
from functools import partial

# Import jax modules
import jax
import jax.numpy as jnp
from jax import jit
from jax import Array
from numpy.typing import ArrayLike
from jax.scipy.special import zeta
from jax.numpy import pi as Pi


# To load pickle files
import pickle
import gzip

jax.config.update("jax_enable_x64", True)

from flint import fmpz, fmpz_mat




def extended_euclidean(w):
    r"""
    **Description:**
    Computes the GCD and Bézout's identity using the extended euclidean algorithm. Also computes an integer
    basis transformation Lambda that brings the input array to form (gcd,0,...,0).
    
    Args:
        w (ArrayLike): Input array.

    Returns:
        tuple (tuple): (Bezout,GCD,Lambda)
        
    """
    
    w = np.asarray(w)
    nonvan_flag = (w!=0)
    van_flag = (w==0)
    nonvan_pos = np.where(nonvan_flag)[0]
    van_pos = np.where(van_flag)[0]

    Bezout = np.zeros(len(w),dtype=int)

    if sum(nonvan_flag)==1:
        GCD = w[nonvan_flag][0]
        Bezout[nonvan_flag] = 1
        Lambda_final = np.identity(len(w),dtype=int)
        Lambda_final[0][0]=0
        Lambda_final[nonvan_pos[0]][nonvan_pos[0]]=0
        Lambda_final[0][nonvan_pos[0]]=1
        Lambda_final[nonvan_pos[0]][0]=1
        
    else:
        v = w[nonvan_flag]

        acoeff = np.abs(v)
        reordering = np.flip(np.argsort(acoeff))
        acoeffsorted = acoeff[reordering]
        Lambda = np.array([np.eye(1,len(reordering),i,dtype=int)[0] for i in reordering])

        dim_red = 0
        while True:
            divs = acoeffsorted[:-1]/acoeffsorted[-1]
            qs = divs.astype(int)
            rs = np.rint(((divs-qs)*acoeffsorted[-1])).astype(int)+np.arange(len(divs))*1e-10
            rssorted = np.flip(np.sort(rs))
  
            perm = np.array([i==rs for i in rssorted],dtype=int)
            acoeffsorted = np.rint(np.concatenate(([acoeffsorted[-1]],rssorted))).astype(int)
            LambdaNext0 = np.block([[qs,np.transpose([[1]])],[perm,np.transpose([np.zeros(len(perm))])]]).astype(int)
            LambdaNext = np.block([[LambdaNext0,np.zeros([len(LambdaNext0),dim_red])],[np.zeros([dim_red,len(LambdaNext0)]),np.identity(dim_red)]])
            Lambda = LambdaNext@Lambda
            
            posnonvan = np.where(acoeffsorted>0)[0]
            posvan = np.where(acoeffsorted==0)[0]
            acoeffsorted = acoeffsorted[posnonvan]
            dim_red = dim_red+len(posvan)

            if len(acoeffsorted)==1:
                break

        Bezout0 = (np.rint(np.transpose(np.linalg.inv(Lambda))[0])*np.sign(v)).astype(int)
        Lambda0 = (np.rint(np.transpose(np.linalg.inv(Lambda)))*np.sign(v)).astype(int)
        Lambda_tilde = np.block([[np.zeros([len(Lambda0),len(w)-len(Lambda0)],dtype=int),Lambda0]
                                 ,[np.identity(len(w)-len(Lambda0),dtype=int),np.zeros([len(w)-len(Lambda0),len(Lambda0)],dtype=int)]])
        
        
        Lambda_final = np.identity(len(w),dtype=int)
        Lambda_final[nonvan_pos] = Lambda_tilde.T[len(w)-len(Lambda0):len(Lambda_tilde)]
        Lambda_final[van_pos] = Lambda_tilde.T[0:len(w)-len(Lambda0)]
        Lambda_final = Lambda_final.T
        
        GCD = np.rint(sum(Bezout0*v)).astype(int)

        Bezout[nonvan_flag] = Bezout0
        
    return (Bezout,GCD,Lambda_final)

def orthogonal_lattice(gens_in):
    r"""
    **Description:**
    Returns the generators of the lattice orthogonal to the lattice generated by gens_in.

    Args:
        gens_in (list): List of generators of the input lattice.
    
    Returns:
        list: List of generators of the orthogonal lattice.
        
    """
    gens = np.array(gens_in)
    d = len(gens)
    n = len(gens[0])
    exponent = (n-1)/2 + (n-d)*(n-d-1)/4
    c = int(np.ceil((2**exponent)*np.prod([np.linalg.norm(g) for g in gens])))
    b_T = np.concatenate((c*gens,np.identity(n, dtype=int)))
    b_T_mat = fmpz_mat(b_T.T.tolist())
    #print("MAYBE THIS IS A BAD IDEA!")
    #b_T_mat = np.array(b_T.T.tolist())
    b_T_lll = [[int(ii) for ii in i][-n:] for i in np.array(b_T_mat.lll().tolist(), dtype=int)[:n-d]]
    return b_T_lll

def get_basis_transformation(coninop):
    r"""
    **Description:**
    Computes the basis transformation to transform charges of a curve to (1,0,...,0).

    Args:
        coninop (ArrayLike): List of conifold charges.
        
    Returns:
        ArrayLike: Basis transformation matrix.
    """
    matrix = [extended_euclidean(coninop)[0].tolist()]
    
    matrix = matrix + orthogonal_lattice([coninop])
    
    return np.array(matrix)

def getAMatrix(intnumstensor):
    r"""
    **Description:**
    Computes the :math:`a`-matrix from the intersection number tensor.
    Args:
        intnumstensor (ArrayLike): Intersection number tensor.
    
    Returns:
        ArrayLike: :math:`a`-matrix.
    """
    
    h11 = len(intnumstensor)
    #return np.array([[intnumstensor[i][i][j]/2 if i<j else intnumstensor[i][j][j]/2 for j in range(h11)] for i in range(h11)])
    return np.array([[intnumstensor[i][j][j]/2 if i<j else intnumstensor[i][i][j]/2 for j in range(h11)] for i in range(h11)])






